name: Trigger Mirror Sync

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger mirror repo
        run: |
          set -e
          curl -fk -X POST https://api.github.com/repos/ylohnitram/tfs-web-fe/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GH_PAT_MIRROR }}" \
            -d '{"event_type": "mirror_trigger"}'
